import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const packageRoot = resolve(import.meta.dirname, "..");
const generatedPath = resolve(packageRoot, "../database/src/schema/auth.generated.ts");
const runtimePath = resolve(packageRoot, "../database/src/schema/auth.ts");
const generated = readFileSync(generatedPath, "utf8");
const adapted = generated
  .replace(/\bpgTable,\s*/, "")
  .replace(
    'from "drizzle-orm/pg-core";\n',
    'from "drizzle-orm/pg-core";\nimport { littlearcSchema } from "./schema.js";\n',
  )
  .replaceAll("pgTable(", "littlearcSchema.table(");

writeFileSync(
  runtimePath,
  `// Generated by Better Auth 1.6.23, then namespaced into the accepted littlearc schema.\n${adapted}`,
  "utf8",
);

console.log("Adapted the pinned Better Auth schema to the LittleArc namespace.");
