import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createOpenApiDocument } from "./document.js";

const packageRoot = fileURLToPath(new URL("../..", import.meta.url));
const generatedJsonPath = `${packageRoot}/src/generated/openapi.json`;
const generatedDocumentPath = `${packageRoot}/src/generated/openapi-document.ts`;
const generatedTypesPath = `${packageRoot}/src/generated/openapi-types.ts`;
const baselinePath = `${packageRoot}/baseline/openapi-v1-baseline.json`;

function writeJson(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

const document = createOpenApiDocument();

writeJson(generatedJsonPath, document);
mkdirSync(dirname(generatedDocumentPath), { recursive: true });
writeFileSync(
  generatedDocumentPath,
  `// Generated by pnpm --filter @littlearc/contracts generate. Do not edit manually.\nexport const openApiDocument = ${JSON.stringify(document, null, 2)} as const;\n`,
);

execFileSync("pnpm", ["exec", "openapi-typescript", generatedJsonPath, "-o", generatedTypesPath], {
  cwd: packageRoot,
  stdio: "inherit",
});

if (!existsSync(baselinePath)) {
  writeJson(baselinePath, document);
}
