packages:
  - apps/*
  - packages/*

overrides:
  "@infinitered/react-native-mlkit-core": 5.0.0

minimumReleaseAgeExclude:
  - "@expo/cli@57.0.9"
  - "@expo/metro-config@57.0.6"
  - "@expo/prebuild-config@57.0.8"
  - expo-application@57.0.2
  - expo-asset@57.0.6
  - expo-build-properties@57.0.6
  - expo-constants@57.0.6
  - expo-dev-client@57.0.7
  - expo-dev-launcher@57.0.7
  - expo-dev-menu@57.0.7
  - expo-image-picker@57.0.5
  - expo-modules-autolinking@57.0.8
  - expo-modules-core@57.0.6
  - expo-notifications@57.0.6
  - expo@57.0.7
  - "@asteasolutions/zod-to-openapi@9.1.0"
  - drizzle-kit@0.31.10
  - drizzle-orm@0.45.2

allowBuilds:
  "@prisma/client": false
  better-sqlite3: false
  esbuild: true
  sharp: true
