packages:
  - apps/*
  - packages/*

overrides:
  "@infinitered/react-native-mlkit-core": 5.0.0

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.9 || 57.0.10'
  - '@expo/metro-config@57.0.6 || 57.0.7'
  - '@expo/prebuild-config@57.0.8 || 57.0.9'
  - expo-application@57.0.2
  - expo-asset@57.0.6 || 57.0.7
  - expo-build-properties@57.0.6 || 57.0.7
  - expo-constants@57.0.6 || 57.0.7
  - expo-dev-client@57.0.7 || 57.0.8 || 57.0.9
  - expo-dev-launcher@57.0.7 || 57.0.8 || 57.0.9
  - expo-dev-menu@57.0.7 || 57.0.8 || 57.0.9
  - expo-image-picker@57.0.5 || 57.0.6
  - expo-modules-autolinking@57.0.8 || 57.0.9
  - expo-modules-core@57.0.6 || 57.0.7
  - expo-notifications@57.0.6 || 57.0.7
  - expo@57.0.7 || 57.0.8
  - "@asteasolutions/zod-to-openapi@9.1.0"
  - drizzle-kit@0.31.10
  - drizzle-orm@0.45.2
  - '@expo/config-plugins@57.0.6'
  - '@expo/config@57.0.6'
  - '@expo/fingerprint@0.20.6'
  - '@expo/image-utils@0.11.4'
  - '@expo/metro-runtime@57.0.7'
  - '@expo/require-utils@57.0.4'
  - '@expo/router-server@57.0.4'
  - babel-preset-expo@57.0.4
  - expo-modules-jsi@57.0.4
  - expo-linking@57.0.4
  - expo-local-authentication@57.0.2
  - expo-router@57.0.8
  - expo-web-browser@57.0.2

allowBuilds:
  "@prisma/client": false
  better-sqlite3: false
  esbuild: true
  sharp: true
